name: ${artifactId}
version: ${version}
author: realEntwickler
description: This is the managing system for our proxies at LostName.eu
website: https://www.lostname.eu
main: eu.lostname.lostproxy.LostProxy
depends:
  - LuckPerms
  - CloudNet-Bridge
  - CloudNet-SyncProxy